import { fonts } from "../utils/typography";

const theme = {
  active: "#00C7BE",
  lightActive: "#04e0d6",
  inActive: "#929299",
  dark: "#2C3434",
  light: "#949793",
  unselectedColor: "#e9ebf0",
  inActiveColor: "rgba(80, 176, 193,.5)",
  black: "#050708",
  whiteOpacity90: "#ffffffdd",
  white: "#ffffff",
  coldLight: "#f9f9f9",
  gray: "#D9D9D9",
  grayLight: "rgba(0, 0, 0, 0.19)",
  lightAsh: "#D2D4D6",
  lightGreen: "#8bdae1",
  cyanGreen: "#89e0ec",
  inactiveText: "#8F8F8F",
  grayUnderline: "#CFCFCF",
  red: "#a32424",
  danger: "#d9534f",
  steelGrey: "#7D848D",
  infoBlack: "#33384B",
  lightGray: "#F4F4F6",
  lightBlue: "#81809E",
  infoText: "#7D848D",
  darkGrey: "#575757",
  yellow: "#FFD233",
  textAreaBorder: "#92929980",
  border: "#ccc",
  darkBlack: "#0E0E0E",
  emailColor: "#71727A",
  activeSearch: "#00C7BE",
};
export default theme;

export const TYPOGRAPHY_STYLES = {
  body: {
    fontFamily: fonts.LIGHT,
    fontWeight: "600",
    fontSize: 64,
    lineHeight: 84,
  },
  titletext: {
    fontFamily: fonts.BOLD,
    fontWeight: "600",
    fontSize: 19,
    lineHeight: 30,
  },
  description: {
    fontFamily: fonts.REGULAR,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 18,
  },
  descriptionText: {
    fontFamily: fonts.REGULAR,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 20,
  },
  questonstext: {
    fontFamily: fonts.REGULAR,
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
  },
  name: {
    fontFamily: fonts.REGULAR,
    fontWeight: "500",
    fontSize: 12,
    lineHeight: 18,
  },
  support: {
    fontFamily: fonts.BOLD,
    fontWeight: "600",
    fontSize: 12,
    lineHeight: 16,
  },
  header: {
    fontFamily: fonts.MEDIUM,
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
  },
  points: {
    fontFamily: fonts.MEDIUM,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 29,
  },
  loyaltyPointsinfo: {
    fontFamily: fonts.MEDIUM,
    fontSize: 10,
    fontWeight: "400",
    lineHeight: 24,
  },
  level: {
    fontFamily: fonts.MEDIUM,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 24,
  },
  firstname: {
    fontFamily: fonts.MEDIUM,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 24,
  },
  xsmax: {
    fontSize: 15,
    fontFamily: fonts.MEDIUM,
    lineHeight: 25,
    fontWeight: "500",
  },
  smax: {
    fontSize: 11,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "400",
  },
  sm: {
    fontSize: 16,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "500",
  },
  smmd: {
    fontSize: 17,
    fontFamily: fonts.SEMIBOLD,
    lineHeight: 35,
    fontWeight: "500",
  },
  md: {
    fontSize: 18,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "500",
  },
  lg: {
    fontSize: 24,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "500",
  },
  xl: {
    fontSize: 32,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "500",
  },
  xxl: {
    fontSize: 48,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "500",
  },
  xxxl: {
    fontSize: 64,
    fontFamily: fonts.BOLD,
    lineHeight: 18,
    fontWeight: "500",
  },
  textInfo: {
    fontFamily: fonts.REGULAR,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 18,
  },
  datechecker: {
    fontFamily: fonts.REGULAR,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
  },
  textdescription: {
    fontFamily: fonts.REGULAR,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 18,
  },
  discountprice: {
    fontFamily: fonts.REGULAR,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 18,
  },
  descriptionInfo: {
    fontFamily: fonts.REGULAR,
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 18,
  },

  status: {
    fontFamily: fonts.BOLD,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "400",
  },
  buttonVariant: {
    fontFamily: fonts.MEDIUM,
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 20,
    mdlgText: {
      fontFamily: fonts.BOLD,
      fontWeight: "600",
      fontSize: 14,
      lineHeight: 21,
    },
    mdlgText2: {
      fontFamily: fonts.BOLD,
      fontWeight: "800",
      fontSize: 16,
      lineHeight: 21,
    },
    smText: {
      fontFamily: fonts.REGULAR,
      fontWeight: "500",
      fontSize: 9,
      lineHeight: 14,
    },
    otptext: {
      fontFamily: fonts.BOLD,
      fontWeight: "800",
      fontSize: 16,
      lineHeight: 20,
    },
  },
};

export type TypographyVariant = keyof typeof TYPOGRAPHY_STYLES;
